#!/bin/bash

set -eufo pipefail

COLS=$(($(tput cols)-5))

NAMESPACE=${1:-kube-system}
DEFAULT_OBJECTS="services daemonsets deployments pods replicasets replicationcontrollers"
OPTS="${@:2}"

if [[ $OPTS =~ ^\+ ]]; then
  OPTS=$(echo ${OPTS} | sed 's/^\+//')
  OBJECTS="$OPTS $DEFAULT_OBJECTS"
else
  OBJECTS=${OPTS:-'services daemonsets deployments pods replicasets replicationcontrollers'}
fi

printf "=%.0s" $(seq 1 $(($COLS-${#NAMESPACE})))
printf " ${NAMESPACE} ===\n"

for OBJECT in ${OBJECTS}; do
  printf "=== $OBJECT "
  printf "=%.0s" $(seq 1 $(($COLS-${#OBJECT})))
  printf "\n"
  kubectl "--namespace=${NAMESPACE}" get ${OBJECT} --show-all
  printf "\n"
done
